### ISSUE TITLE
Tag a release, pretty please? :)

### ISSUE THREAD

**Issue by runiq** [Tr3m/nam-juce#2]
Heya,

Thanks a lot for making this! :) I'm looking at it with considerable interest. I've packaged [neural-amp-modeler-lv2](https://github.com/mikeoliphant/neural-amp-modeler-lv2) for Flathub, and I'd like to package your implementation too because it supports more targets.

Is this far along enough that you can justify tagging it?

**Comment by Tr3m** [comment]
Hello there, thanks, I appreciate the interest.

I haven't tagged a release for the time being, mainly for two reasons. First, I haven't tested as much as i'd like on Linux to feel confortable doing so yet. Second, I'm currently working on an update to accommodate some of the changes the NeuralAmpModelerCore has gone through since I started the project.

Unfortunately I cant promise a time frame for release at the moment, but it should be sooner rather than later :)

**Comment by runiq** [comment]
No worries, then, take your time. :)
