### ISSUE TITLE
Eigan Module Link

### ISSUE THREAD

**Issue by smire312** [Tr3m/nam-juce#4]
I'm getting a 404 error on the Eigen module repository (eigen @ 7d9bb90). Is there an updated link?

**Comment by Tr3m** [comment]
I'm assuming when you say 404 error you mean when you click the submodule folder on github, given that cloning and initializing seems to be working just fine.
This may be a github issue, probably because the eigen repo is hosted on gitlab. You can always find and follow the submodule upstream URLs from the ```.gitmodules``` file.
